# Generated by Django 6.0.4 on 2026-05-24 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('q1', models.TextField(blank=True, help_text='Detection methodology')),
                ('q2', models.TextField(blank=True, help_text='Handling uncertain AI outputs')),
                ('q3', models.TextField(blank=True, help_text='AI bias mitigation')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('FAKE', 'Fake'), ('REAL', 'Real'), ('UNCERTAIN', 'Uncertain / Cannot Determine')], max_length=20)),
                ('confidence', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('reasoning', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_cached_result', models.BooleanField(default=False)),
                ('siglip_prob', models.FloatField(blank=True, null=True)),
                ('xception_prob', models.FloatField(blank=True, null=True)),
                ('efficientnet_prob', models.FloatField(blank=True, null=True)),
                ('model_ensemble_prob', models.FloatField(blank=True, null=True)),
                ('model_ensemble_verdict', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Expert Review'), ('REVIEWED', 'Expert Reviewed')], default='PENDING', max_length=20)),
                ('final_verdict', models.CharField(blank=True, max_length=20)),
                ('final_confidence', models.FloatField(blank=True, null=True)),
                ('expert_review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='detector.expertreview')),
                ('original_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_duplicates', to='detector.scanresult')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
